import BottomBar from '@app/components/layout/BottomBar'
import LeftSideBar from '@app/components/layout/LeftSideBar'
import MainContainer from '@app/components/layout/MainContainer'
import RightSideBar from '@app/components/layout/RightSideBar'
import TopBar from '@app/components/layout/TopBar'
import { ClerkProvider } from '@clerk/nextjs'
import "../globals.css"
import {Inter} from "next/font/google"
// import RightSideBar from '../components/layout/RightSideBar'
// import LeftSideBar from '../components/layout/LeftSideBar'
// import MainContainer from '../components/layout/MainContainer'
// import TopBar from '../components/layout/TopBar'
// import BottomBar from '../components/layout/BottomBar'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const inter = Inter({subsets:["latin"]})
export default function RootLayout({ children }) {
 return (
  <ClerkProvider>
    <html lang="en">
      <body className={`${inter.className} bg-purple-2`} >
        <main className='flex flex-row'>
        <LeftSideBar/>
        <MainContainer>
        {children}
        </MainContainer>
        <RightSideBar/>
        </main>
        <BottomBar/>
        </body>
    </html>
    </ClerkProvider>
  )
}
